import { Container, Header } from "@/shared/components/shared";
import Footer from "@/shared/components/shared/footer";
import TopHeader from "@/shared/components/shared/top-header";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Next Pizza | Корзина",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="min-h-screen bg-[#F2F3F5]">
      <Suspense>
        <TopHeader/>
        <Header
          hasSearch={true}
          hasCart={true}
          className="border-b-gray-200"
        />
      </Suspense>
      <Container>{children}</Container>
      <Footer/>
    </main>
  );
}
